#!/bin/bash

set -e
set -u

echo "> creating release"
bosh create release --final --with-tarball | tee .dev_builds/publish-release

RELEASE_VERSION=$(grep 'Release version' .dev_builds/publish-release | awk -F ': ' '{ print $2 }')
RELEASE_TARBALL=$(grep 'Release tarball' .dev_builds/publish-release | awk -F ': ' '{ print $2 }')

BUCKET_NAME=$(cat config/final.yml | grep 'bucket_name' | awk -F ': ' '{ print $2 }')

git add -A .final_builds releases
git commit -m "Release $RELEASE_VERSION"

echo "> uploading release ($RELEASE_VERSION)"
aws s3api put-object --bucket "$BUCKET_NAME" --key "release/$RELEASE_VERSION.tgz" --body "$RELEASE_TARBALL"

echo "> uploading release (latest)"
aws s3api put-object --bucket "$BUCKET_NAME" --key "release/latest.tgz" --body "$RELEASE_TARBALL"
